from pathlib import Path
import os
import re
import subprocess

Import("env")

PROJECT_DIR = Path(env.subst("$PROJECT_DIR")).resolve()
REPO_ROOT = PROJECT_DIR.parents[1]
HEADER_PATH = PROJECT_DIR / "include" / "a21_firmware_build.generated.h"


def resolve_commit():
    explicit = os.environ.get("A21_FIRMWARE_COMMIT", "").strip()
    if explicit:
        return explicit
    try:
        return subprocess.check_output(
            ["git", "rev-parse", "--short=12", "HEAD"],
            cwd=str(REPO_ROOT),
            text=True,
            stderr=subprocess.DEVNULL,
        ).strip()
    except Exception:
        return "dev"


def validate_commit(commit):
    if commit == "dev":
        return commit
    if not re.fullmatch(r"[0-9a-fA-F]{7,40}", commit):
        raise ValueError("A21_FIRMWARE_COMMIT must be a git sha or dev")
    if "x21" in commit.lower() or "v21" in commit.lower():
        raise ValueError("A21_FIRMWARE_COMMIT contains forbidden legacy identity")
    return commit


commit = validate_commit(resolve_commit())
HEADER_PATH.write_text(
    "#pragma once\n"
    "\n"
    "/* Generated by A21 PlatformIO pre-build script. Do not commit. */\n"
    f"#define A21_FIRMWARE_COMMIT \"{commit}\"\n",
    encoding="utf-8",
)
